# Generated by Django 6.0.3 on 2026-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('diary', 'Diary'), ('dev', 'Dev Log'), ('music', 'Music'), ('art', 'Art'), ('world', 'World')], max_length=20)),
            ],
        ),
    ]
